name: Build and push the base image

on:
  push:
    paths:
      - Dockerfile.base
      - .github/workflows/build-base.yml
    branches:
      - develop
      - 'feat/**'
      - 'feature/**'

# we want to be able to trigger this manually
  workflow_call:

  workflow_dispatch:

  schedule:
    - cron:  '0 22 * * *'

jobs:
  ubuntu-base-build:
    name: Build and configure the latest base image
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repo Files
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Get GitHub organization or user
        run: echo 'ORG='$(echo $(dirname ${GITHUB_REPOSITORY}) | awk '{print tolower($0)}') >> $GITHUB_ENV
      - name: Set version
        id: version
        run: |
          version=$(date '+%Y-%m-%d').${{ github.run_number }}.$(echo ${{ github.sha }} | cut -c1-7)
          echo "version=$version" | tee -a "$GITHUB_OUTPUT"
      - name: GitHub app JWT and installation access token generation
        uses: jamestrousdale/github-app-jwt-token@0.1.4
        id: generate-github-app-tokens
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
        
      - name: Build the Docker image
        uses: ./.github/actions/docker-build
        id: build
        with:
          project: hmpps-github-actions-runner-base
          push: True
          dockerfile: Dockerfile.base
          version: ${{ steps.version.outputs.version }}
          gh_auth_token: ${{ steps.generate-github-app-tokens.outputs.access-token }}
    permissions:
      contents: read
      packages: write
      pull-requests: write
      
  delete-old-base-images:
    runs-on: ubuntu-latest
    needs:
      ubuntu-base-build
    steps:
      - name: Delete old gchr.io images for runner base
        uses: actions/delete-package-versions@v5
        with:
          package-name: hmpps-github-actions-runner-base
          package-type: container
          min-versions-to-keep: 10
          delete-only-untagged-versions: false
    permissions:
      contents: read
      packages: write
      pull-requests: write